server:
  port: 8081
  servlet:
    contextPath: /chitchat/
spring:
  mvc:
    locale: en
  #datasource:
  #  driver-class-name: com.mysql.cj.jdbc.Driver
  #  url: jdbc:mysql://localhost:3306/chitchat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  #  username: root
  #  password: root1234
  #jpa:
  #  properties:
  #    hibernate:
  #      ddl-auto: none
  #      default_schema: chitchat
  #      dialect: org.hibernate.dialect.MySQL8Dialect
  #      format_sql: true
  #      show_sql: true
  #      type: trace
  #      use_sql_comments: true
  #  open-in-view: false
  main:
    lazy-initialization: false
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8
  #security:
  #  oauth2:
  #    client:
  #      registration:
  #        facebook:
  #          client-id: 1006299956442971
  #          client-secret: b344b25016ff3734de8253f8759e6b09