server:
  port: 8081
  servlet:
    contextPath: /chitchat/
spring:
  mvc:
    locale: en
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:chitchat
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  main:
    lazy-initialization: false
  http:
    encoding:
      enabled: true
      force: true
      charset: UTF-8